#!/bin/bash

#############################################
# Health Report Generator
# Micro-Security Gateway
#############################################

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
GATEWAY_URL="${GATEWAY_URL:-https://gateway-api.your-subdomain.workers.dev}"
ADMIN_TOKEN="${ADMIN_TOKEN:-}"
REPORT_DATE="${1:-$(date +%Y-%m-%d)}"
OUTPUT_FILE="health-report-${REPORT_DATE}.md"

echo "=========================================="
echo "Health Report Generator"
echo "Micro-Security Gateway"
echo "=========================================="
echo ""
echo "Report Date: $REPORT_DATE"
echo "Output File: $OUTPUT_FILE"
echo ""

# Check if admin token is set
if [ -z "$ADMIN_TOKEN" ]; then
    echo -e "${RED}Error: ADMIN_TOKEN environment variable not set${NC}"
    echo "Usage: ADMIN_TOKEN=xxx ./scripts/generate-health-report.sh [YYYY-MM-DD]"
    exit 1
fi

# Create report file
cat > "$OUTPUT_FILE" << EOF
# Daily Health Report
## Micro-Security Gateway - $REPORT_DATE

**Generated**: $(date '+%Y-%m-%d %H:%M:%S UTC')
**Period**: Last 24 hours
**Environment**: Production

---

## Executive Summary

EOF

echo "Gathering health metrics..."

# Fetch metrics from admin endpoints
echo "Fetching metrics..." >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Get general metrics
METRICS=$(curl -s -H "Authorization: Bearer $ADMIN_TOKEN" "${GATEWAY_URL}/api/admin/metrics")

if [ -n "$METRICS" ]; then
    echo "### System Metrics" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "$METRICS" | jq '.' >> "$OUTPUT_FILE" 2>/dev/null || echo "Could not parse metrics JSON"
    echo "" >> "$OUTPUT_FILE"
fi

# Get circuit breaker status
CIRCUIT_BREAKER=$(curl -s -H "Authorization: Bearer $ADMIN_TOKEN" "${GATEWAY_URL}/api/admin/circuit-breaker")

if [ -n "$CIRCUIT_BREAKER" ]; then
    echo "### Circuit Breaker Status" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "$CIRCUIT_BREAKER" | jq '.' >> "$OUTPUT_FILE" 2>/dev/null || echo "Could not parse circuit breaker JSON"
    echo "" >> "$OUTPUT_FILE"
fi

# Get provider health
PROVIDER_HEALTH=$(curl -s -H "Authorization: Bearer $ADMIN_TOKEN" "${GATEWAY_URL}/api/admin/provider-health")

if [ -n "$PROVIDER_HEALTH" ]; then
    echo "### Provider Health" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "$PROVIDER_HEALTH" | jq '.' >> "$OUTPUT_FILE" 2>/dev/null || echo "Could not parse provider health JSON"
    echo "" >> "$OUTPUT_FILE"
fi

# Get cost information
COSTS=$(curl -s -H "Authorization: Bearer $ADMIN_TOKEN" "${GATEWAY_URL}/api/admin/costs")

if [ -n "$COSTS" ]; then
    echo "### Cost Tracking" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "$COSTS" | jq '.' >> "$OUTPUT_FILE" 2>/dev/null || echo "Could not parse costs JSON"
    echo "" >> "$OUTPUT_FILE"
fi

# Add performance analysis section
cat >> "$OUTPUT_FILE" << EOF

## Performance Analysis

### Latency Distribution

| Metric | Target | Actual | Status |
|--------|--------|--------|--------|
| P50 Latency | < 500ms | TBD | - |
| P95 Latency | < 2000ms | TBD | - |
| P99 Latency | < 5000ms | TBD | - |

### Error Rate Analysis

| Period | Error Rate | Target | Status |
|--------|------------|--------|--------|
| Last Hour | TBD | < 5% | - |
| Last 6 Hours | TBD | < 5% | - |
| Last 24 Hours | TBD | < 5% | - |

### Throughput Metrics

| Metric | Value |
|--------|-------|
| Total Requests | TBD |
| Requests per Second | TBD |
| Peak Throughput | TBD |

## Incident Summary

### Critical Incidents (Sev 1-2)
None reported

### Warnings (Sev 3-4)
None reported

## Recommendations

1. Monitor P95 latency closely
2. Review cost trends weekly
3. Check circuit breaker activations
4. Verify provider health status

## Next Steps

- Continue monitoring for 24 hours
- Review and update runbook if needed
- Schedule performance optimization review

---

**Report Generated By**: Automated Health Report System
**For Questions**: Contact on-call team
EOF

echo -e "${GREEN}✓${NC} Health report generated: $OUTPUT_FILE"

# Display summary
echo ""
echo "=========================================="
echo "Report Summary"
echo "=========================================="
echo "File: $OUTPUT_FILE"
echo "Size: $(wc -c < "$OUTPUT_FILE") bytes"
echo ""

# Ask if user wants to view the report
read -p "View report now? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    if command -v less &> /dev/null; then
        less "$OUTPUT_FILE"
    else
        cat "$OUTPUT_FILE"
    fi
fi

echo ""
echo -e "${GREEN}✓${NC} Report generation complete"
