name = "gateway-api"
main = "src/index.ts"
compatibility_date = "2024-03-10"

[[d1_databases]]
binding = "DB"
database_name = "ms-gateway-db"
database_id = "c41c1616-fc55-42c0-bbca-65c782da1342"
migrations_dir = "../../packages/db/migrations"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "736bbb8ca70144609f4c411ed9a414d4"

[vars]
ENVIRONMENT = "development"
SUPABASE_URL = "https://yyfwepdlvcubthmeldir.supabase.co"
# SUPABASE_JWT_SECRET will be added as a secret via wrangler secret put
