name = "gateway-api"
main = "src/index.ts"
compatibility_date = "2024-03-10"

# [[d1_databases]]
# binding = "DB"
# database_name = "ms-gateway-db"
# database_id = "to-be-created"

# [[kv_namespaces]]
# binding = "KV"
# id = "to-be-created"

[vars]
ENVIRONMENT = "development"
